Use apt lua5.3 instead of source build
  For using source build liblua.a will cause original cartographer
  build error, "undefined reference to `dlopen'".